# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/migrate ./cmd/migrate
COPY internal/config ./internal/config
COPY ./application.yaml ./application.yaml

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /migrate ./cmd/migrate

ENTRYPOINT ["/migrate"]
