version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
      - POSTGRES_USER=app_user
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: 'postgres:14'
    ports:
      - "5432:5432"
    networks:
      - app-tier
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d app -U app_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    environment:
      - DATABASE_HOST=postgresql:5432
    build:
      dockerfile: Dockerfile.migrations
      context: .
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - app-tier

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=postgresql:5432
    networks:
      - app-tier
    depends_on:
      - migrations
